const locations = {
  Alä: "Almnäs",
  Arnc: "Arlanda",
  Arne: "Arlanda nedre",
  Arnn: "Arlanda N",
  Arns: "Arlanda S",
  Bkb: "Barkarby",
  Bjn: "Björnkulla",
  Bre: "Bränninge",
  Brny: "Bro Nygård",
  Bro: "Bro",
  Bvr: "Blackvreten",
  Bra: "Brista",
  Bäl: "Bällsta",
  Duo: "Duvbo",
  Dån: "Dånviken",
  Cst: "Stockholm C",
  Fas: "Farsta strand",
  Flb: "Flemingsberg",
  Gdv: "Gröndalsviken",
  Ghu: "Gula huset",
  Hak: "Hallstavik",
  Hel: "Helenelund",
  Hfa: "Hemfosa",
  Hgl: "Hagalund",
  Hgv: "Häggvik",
  Hlö: "Hölö",
  Gau: "Garnudden",
  Hnd: "Handen",
  Jbo: "Jordbro",
  Hu: "Huddinge",
  Jkb: "Jakobsberg",
  Huv: "Huvudsta",
  Jn: "Järna",
  Hön: "Högdalen",
  Khä: "Kallhäll",
  Kda: "Krigslida",
  Ke: "Karlberg",
  Kmy: "Kummelby",
  Kän: "Kungsängen",
  Mr: "Märsta",
  Lm: "Liljeholmen",
  Nkv: "Nykvarn",
  Msj: "Malmsjö",
  Nst: "Stockholms norra",
  Nvk: "Norrviken",
  Nyh: "Nynäshamn",
  Mö: "Mölnbo",
  Nba: "Nyboda",
  Nbt: "Norra bantorget",
  Ngd: "Nynäsgård",
  R: "Rotebro",
  Ryb: "Ryssjöbrink",
  Sod: "Sthlm Odenplan",
  So: "Solna",
  Sol: "Sollentuna",
  Rön: "Rönninge",
  Skby: "Skavstaby",
  Skg: "Skogås",
  Spå: "Spånga",
  Rs: "Rosersberg",
  Sub: "Sundbyberg",
  Sst: "Stockholms södra",
  Sci: "Stockholm City",
  Ssä: "Segersäng",
  Sta: "Stuvsta",
  Vga: "Vega",
  wGåb: "Gåshaga brygga",
  wGåh: "Gåshaga",
  Udl: "Ulriksdal",
  wHlt: "Höglandstorget",
  Vhe: "Västerhaninge",
  wHöb: "Högberga",
  Söc: "Södertälje C",
  Söd: "Södertälje hamn",
  Södy: "Söderby",
  Söka: "Södertälje kanal",
  Upv: "Upplands Väsby",
  Söu: "Södertälje Syd",
  Uts: "Utsikten",
  Söö: "Södertälje S",
  wKlv: "Klövervägen",
  Tm: "Tomteboda bangård",
  wKoa: "Kottla",
  Tmö: "Tomteboda övre",
  wKäp: "Käppala",
  wAga: "Aga",
  wLab: "Larsberg",
  wAll: "Alléparken",
  wAlv: "Alvik",
  wSms: "Smedslätten",
  wBag: "Baggeby",
  wSkr: "Skärsätra",
  wBod: "Bodal",
  Tot: "Toresta",
  wBvi: "Brevik",
  Vn: "Värtan",
  wNob: "Nockeby",
  wNot: "Nockeby torg",
  wTov: "Torsvik",
  wOll: "Olovslund",
  wÅlG: "Ålstens Gård",
  Ts: "Tungelsta",
  wRos: "Ropsten",
  wÅls: "Ålstensgatan",
  Tu: "Tumba",
  Tul: "Tullinge",
  xFsu: "Frösunda",
  xFsä: "Fisksätra",
  Tåd: "Trångsund",
  xMnb: "Molnby",
  xAlp: "Altorp",
  xTug: "Tunagård",
  xMöb: "Mörby",
  xGpf: "Galoppfältet",
  xBvv: "Bråvallavägen",
  xTx: "Taxinge-Näsby",
  xNbe: "Näsbyallé",
  xBäl: "Bällsta",
  xTäb: "Täby kyrkby",
  xNbp: "Näsbypark",
  xNeg: "Neglinge",
  xTäc: "Täby Centrum",
  xDje: "Djursholms Ekeby",
  xNka: "Nacka",
  xUnv: "Universitetet",
  xTäl: "Täljö",
  xDjö: "Djursholms Ösby",
  xHed: "Henriksdal",
  xVbm: "Viggbyholm",
  xOta: "Ormsta",
  xEkg: "Ekskogen",
  xEnb: "Enebyberg",
  xVev: "Vendevägen",
  xHgä: "Hägernäs",
  xVis: "Visinge",
  xEvb: "Erstaviksbadet",
  xEsa: "Ensta",
  xVlt: "Vallentuna",
  xRdb: "Rydbo",
  xRnb: "Roslags Näsby",
  xÅbg: "Åkersberga",
  xRvä: "Ringvägen",
  xHön: "Härnön",
  xIgb: "Igelboda",
  xÅru: "Åkers Runö",
  xSbn: "Saltsjöbaden",
  Åbe: "Årstaberg",
  xSdn: "Saltsjö-Duvnäs",
  xSik: "Sickla",
  xÖsk: "Österskär",
  xSlu: "Slussen",
  xSjl: "Saltsjö-Järla",
  xÖga: "Östberga",
  xSln: "Solsidan",
  xKgl: "Kragstalund",
  xÖst: "Stockholms Östra",
  xÖsv: "Östervik",
  xKår: "Kårsta",
  xSsu: "Stocksund",
  xLdm: "Lindholmen",
  xStä: "Storängen",
  xTab: "Tattby",
  xLhl: "Lahäll",
  xTbl: "Tibble",
  xLiä: "Lillängen",
  xTip: "Tippen",
  Öso: "Ösmo",
  Öte: "Östertälje",
  Äs: "Älvsjö",
  Äsg: "Älvsjö godsbangård",
  Kng: "Kvarnängen",
  Bna: "Brunna",
  Bål: "Bålsta",
  Dma: "Dannemora",
  Eko: "Ekolsund",
  Ep: "Enköping",
  Eby: "Ekeby",
  Gib: "Grillby",
  Gmo: "Gimo",
  Hrm: "Hargshamn",
  Hy: "Heby",
  Jla: "Järlåsa",
  Jlo: "Järlebo",
  Kn: "Knivsta",
  Maa: "Marma",
  Mrm: "Marma",
  Meh: "Mehedeby",
  Myn: "Myrbacken",
  Lub: "Lundby",
  Må: "Morgongåva",
  Os: "Orrskog",
  Sam: "Samnan",
  Sas: "Salsta",
  Srv: "Storvreta",
  Sur: "Skutskär",
  Surn: "Skutskär norra",
  Syt: "Skyttorp",
  U: "Uppsala",
  Vha: "Vattholma",
  Säp: "Skärpan",
  Säy: "Säby",
  Una: "Uppsala norra",
  Tip: "Tierp",
  Tbo: "Tobo",
  xFl: "Fyrislund",
  xLöt: "Löt",
  xAlg: "Almunge",
  xMg: "Moga",
  xMl: "Marielund",
  xGa: "Gunsta",
  xB: "Bärby",
  xUö: "Uppsala Östra",
  xF: "Faringe",
  xFb: "Funbo",
  xSa: "Skölsta",
  xÅs: "Årsta",
  xSlä: "Selknä",
  xLbr: "Länna bruk",
  xLh: "Lövstahagen",
  xLna: "Länna",
  Öh: "Örbyhus",
  Äba: "Älvboda",
  Äkb: "Älvkarleby",
  B: "Björnlunda",
  Bgv: "Bälgviken",
  Bt: "Baggetorp",
  Bva: "Barva",
  Ebg: "Enstaberga",
  Et: "Eskilstuna",
  Fle: "Flen",
  Fok: "Folkesta",
  Fsö: "Flens övre",
  Gn: "Gnesta",
  Gru: "Grundbro",
  Hgö: "Högsjö",
  Hnä: "Hälleforsnäs",
  Hål: "Hållsta",
  Häd: "Härad",
  K: "Katrineholm",
  Jår: "Jönåker",
  Kju: "Kjula",
  Koe: "Kolke",
  Ksus: "Kvicksund",
  Lg: "Läggesta",
  Mby: "Malmby",
  Lre: "Lästringe",
  Nsj: "Nyckelsjön",
  Mlö: "Mellösa",
  Oxd: "Oxelösund",
  Nbr: "Nybybruk",
  Nk: "Nyköping",
  Sgs: "Strängnäs",
  Nks: "Nyköping södra",
  Snl: "Skanlog",
  Sh: "Stjärnhov",
  Sii: "Silinge",
  Sp: "Sparreholm",
  Rke: "Rekarne",
  Spn: "Stolpstugan",
  Skrp: "Skogstorp",
  Skv: "Skebokvarn",
  Ssa: "Sjösa",
  Stö: "Strångsjö",
  Sde: "Sköldinge",
  Vhd: "Vagnhärad",
  Tba: "Tystberga",
  Vme: "VME",
  Vr: "Vingåker",
  Vre: "Vrena",
  xMfd: "Mariefred",
  xMfå: "Mariefreds ångbåtsstation",
  xMln: "Marielund",
  xGhn: "Gripsholmsviken",
  xHdt: "Hedlandet",
  xVht: "Värdshuset",
  xHhn: "Hjorthagen",
  Åba: "Ålberga",
  xJbn: "Jagbacken",
  xLgn: "Läggesta nedre",
  Åks: "Åkers styckebruk",
  xSöy: "Sjöbygget"
}

export default location => locations[location] || location
